# Generated by Django 5.0.6 on 2024-05-30 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("fname", models.CharField(default="", max_length=255)),
                ("lname", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255, unique=True)),
                ("password", models.TextField(default="")),
                ("contact", models.CharField(default="", max_length=20, unique=True)),
                ("address", models.TextField(default="")),
                (
                    "profile",
                    models.ImageField(default="User/dummy.png", upload_to="User/"),
                ),
                ("otp", models.IntegerField(default=0)),
                ("otp_count", models.IntegerField(default=0)),
                ("otp_status", models.BooleanField(default=False)),
                ("no_of_attempts_allowed", models.IntegerField(default=3)),
                ("no_of_wrong_attempts", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserWhitelistToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.user",
                    ),
                ),
            ],
        ),
    ]
