# Generated by Django 5.0.6 on 2024-05-23 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("f_name", models.CharField(blank=True, max_length=20, null=True)),
                ("l_name", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("otp", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "otp_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "otp_count",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "profile",
                    models.ImageField(
                        default="admin/ProfileImage/dummy.png",
                        upload_to="admin/ProfileImage/",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("SuperAdmin", "SuperAdmin"), ("Manager", "Manager")],
                        default="Manager",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdminWhitelistToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("token", models.TextField()),
                (
                    "admin_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapi.adminauth",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
