# Generated by Django 5.0.6 on 2024-05-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapi", "0002_brand_productcategory_alter_adminauth_otp_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapi.adminauth",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapi.adminauth",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapi.adminauth",
            ),
        ),
    ]
