# Generated by Django 5.0.6 on 2024-11-20 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapi", "0004_alter_brand_admin_id_alter_product_admin_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="saving",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_products",
                to="adminapi.productcategory",
            ),
        ),
    ]
